### ISSUE TITLE
"Date" type in text behavior does not work correctly

### ISSUE THREAD

**Issue by cperryk** [nymag/clay-kiln#686] opened 2016-11-16 15:39 UTC
Typing a value into one part of the date often resets values in other parts.

To reproduce:
1. Open the settings view of a component with a field with a `text` behavior that has `type` set to `date`.
2. Click the month part and type a number.
3. Click or tab to the day part and type a number.
4. Click or tab to the year part and type a number. You will see month and day values disappear.

Whenever the other parts are reset, this console warning appears: `The specified value "0001-08-01T12:00" does not conform to the required format, "yyyy-MM-dd".`

On: Desktop Chrome 54.0.2840.98

**Comment by nelsonpecora** [comment] 2016-11-21 14:27
Hmm. Can you reproduce this in the date field in the publish pane, or just in a component form? On Chrome, there isn't much date formatting going on (since it uses the native datepicker)

**Comment by cperryk** [comment] 2016-11-21 15:14
@nelsonpecora Just in a component form.

**Comment by fraddski** [comment] 2016-12-22 17:40
@nelsonpecora I can reproduce this - both in settings and inline. It's only happening for `date` types, not `datetime`, so the publish pane isn't affected. Doesn't seem to happen with Firefox or Safari, but both force you to use a datepicker, which is removed from Chrome. Date input types outside of kiln work fine.

**Comment by nelsonpecora** [comment] 2017-03-16 15:54
Let's make sure we test agains this before releasing v1.0

**Comment by nelsonpecora** [comment] 2017-03-28 16:47
I _think_ this may have been fixed by https://github.com/nymag/clay-kiln/pull/793 since I cannot repro it in new kiln

**Closed by nelsonpecora** 2017-03-28 16:47 UTC
Labels: regression
